AnuragBoard/urls.py
from django.contrib import admin
from django.urls import path
from board import views
from accounts import views as account_views
from django.contrib.auth.views import LogoutView,LoginView
import django.contrib.auth.views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.BoardListView.as_view(),name='homepage'),
    path('reset',auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ),name='password_reset'),
    path('reset/done',auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name='password_reset_confirm'),
    path('reset/complete',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('signup/',account_views.signup,name='signup'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('settings/password',auth_views.PasswordChangeView.as_view(template_name='password_change.html'),name='password_change'),
    path('settings/password/done',auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name='password_change'),
    path('logout',LogoutView.as_view(),name='password_change_done'),
    path('login',LoginView.as_view(template_name='login.html',redirect_authenticated_user=True),name='login'),
    path('board/<int:pk>/',views.board_topics,name='board_topics'),
    path('board/<int:pk>/topic/<int:topics_pk>/',views.topic_posts,name='topic_posts'),
    path('board/<int:pk>/topic/<int:topics_pk>/post/<int:post_pk>/edit',views.UpdatePost.as_view(),name='update_post'),
    path('board/<int:pk>/topic/<int:topics_pk>/reply/',views.reply_topic,name='reply_topic'),
    path('board/<int:pk>/new',views.new_topic,name='new_topic'),
    path('user/update',views.UserUpdateView.as_view(),name='user_update')
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from markdown import markdown
from django.utils.html import mark_safe
# Create your models here.


class Board(models.Model):
    name=models.CharField(max_length=40,unique=True)
    description=models.TextField(max_length=500)
    

    def get_post_count(self):
        return Post.objects.filter(topic__board=self).count()
    
    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject=models.CharField(max_length=250)
    last_updated=models.DateTimeField(auto_now_add=True)
    board=models.ForeignKey(Board,related_name="topics",on_delete=models.CASCADE)
    starter=models.ForeignKey(User,related_name="topics",on_delete=models.CASCADE)
    views=models.ManyToManyField(User,related_name='+')


    
    def get_views_count(self):
        return self.views.all().count()

class Post(models.Model):
    message=models.TextField(max_length=4000)
    topic=models.ForeignKey(Topic,related_name="posts",on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(null=True)
    created_by=models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    updated_by=models.ForeignKey(User,related_name='+',null=True,on_delete=models.SET_NULL)



    def get_absolute_url(self):
        return reverse('topic_posts',args=[self.topic.board.pk,self.topic.pk])



    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message,safe_mode='escape'))

board/forms.py
from .models import Topic,Post
from django import forms

class TopicForm(forms.ModelForm):

    message=forms.CharField(widget=forms.Textarea(
    attrs={
    'rows':5,'placeholder':'What is your message'}
    ),max_length=4000,
    help_text="Max length is 4000"
    )

    class Meta:
        model=Topic
        fields=['subject','message']

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['message',]
        

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{%block title%}DjangoBoards{%endblock%}</title>
    {%load static%}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    {% block stylesheet %}{% endblock %}

  </head>
  <body>
    {%block body%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
     
          <a class="navbar-brand" href="{% url 'homepage' %}">Django Boards</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {%if request.user.is_authenticated%}
          <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="#">My account</a>
                  <a class="dropdown-item" href="/settings/password">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </li>
            </ul>
          </div>
        {%else%}
        <form class="form-inline ml-auto">
          <a href="{% url 'login'%}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up

            
          </a>
        </form>
        {%endif%}
      </div>

      </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
            {%block breadcrumb%}
            {%endblock%}
        </ol>
        {%block content%}
        {%endblock%}
    </div>
    {%endblock body%}

    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {%block script%}
  {%endblock%}
</body>
</html>

templates/base_accounts.html
{%extends 'base.html'%}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'homepage' %}">Django Boards</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{%block stylesheet%}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{%endblock%}
{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

{%block script%}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
  let simplemde=new SimpleMDE();
</script>
{%endblock%}

templates/form.html
{%load widget_tweaks %}
{%load form_tags%}
      {%csrf_token%}
    <div class="container">
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
            {% endfor %}
    </div>
    {% endif %}
        {%for field in form%}
        <div class="form-group">
            {{ field.label_tag }}
            
            {%render_field field class=field|input_class%}
            
            {%for error in field.errors%}
                <div class="invalid-feedback d-block">
                    {{error}}
                </div>
            {%endfor%}
           

            {%if field.help_text%}
                <div class="form-text text-muted">
                    {{field.help_text}}
                </div>
            {%endif%}
        </div>
        {%endfor%}
      

    </div>



   

templates/home.html
{%extends 'base.html'%}
{%block breadcrumb%}
    <li class="breadcrumb-item active">Boards</li>
{%endblock%}

{%block content%}
<table class="table">
        <thead class="thead-inverse">
          <tr style="background-color: #2b2929;color: #bbb;"> 
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="board/{{board.pk}}/">{{ board.name }}</a> 
               <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">{{board.get_post_count}}</td>
              <td class="align-middle">{{board.topics.count}}</td>
              <td>
                {%with post_count=board.get_post_count%}

              
                {%with post=board.get_last_post%}
                {%if post_count != 0 %}  
                <a href="/board/{{board.pk}}/topic/{{post.topic.pk}}/" style="text-decoration: none; color:#4082a2;font-size: 1.2em;">
                  <small>
                    
                    By {{post.created_by}} at {{post.created_at}}

                  </small>
                </a>
                {%else%}
                <small class="text-muted">
                  <em>No posts yet.</em>
                </small>
                {%endif%}

                {%endwith%}
                {%endwith%}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

{%endblock%}

templates/login.html
{%extends 'base_accounts.html'%}

{%block content%}

        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h3 class="card-title">Login</h3>
                    <form method="post" novalidate>
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ next }}">
                      {% include 'form.html' %}
                      <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                  </div>
                  <div class="text-center py-2">
                    <small>
                      <a href="#" class="text-muted">Forgot your password?</a>
                    </small>
                  </div>
                  <div class="card-footer text-muted text-center">
                    New to django boards? <a href="{%url 'signup'%}">Sign Up</a>
                  </div>
                </div>
              </div>
        </div>
{%endblock%}

templates/my_account.html
{%extends 'base.html'%}

{%block content%}

<div class="container">
    <form action="" method="POST">
        {%csrf_token%}
        {%include 'form.html'%}
        <button class="btn btn-info">Save</button>
    </form>
</div>


{%endblock%}

templates/new_topic.html
{%extends 'base.html'%}

{%block breadcrumb%}
     <li class="breadcrumb-item">   <a href="/">Boards</a></li>
      <li class="breadcrumb-item">{{ board.name }}</li>
      <li class="breadcrumb-item active">New Topic</li>
{%endblock%}

{%block content%}
{%load widget_tweaks%}

<form method="POST" action=''>
    {%csrf_token%}
    <!-- <div class="form-group">
      <label for="exampleFormControlInput1">Subject</label>
      <input type="text" class="form-control" id="subject" name="subject">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Message</label>
      <textarea class="form-control" id='message' style="height: 233px;" id="exampleFormControlTextarea1" rows="3" name="message"></textarea>
    </div> -->
    
    {%for field in form%}
    <div class="form-group">
      {{field.label_tag}}
      {%if form.is_bound%}
        {%if field.errors%}
          {%render_field field class='form-control is-invalid'%}
          {%for error in field.errors%}
            <small class="invalid-feedback">
              {{error}}
            </small>
          {%endfor%}
        {%else%}
          {%render_field field class='form-control'%}
        {%endif%}

      {%else%}
          {%render_field field class='form-control'%}
      {%endif%}
    </div>
    
  {%endfor%}
    <button class="btn btn-primary" id='subbtn' type="submit">Post</button>
  </form>
  {%block script%}
 
<script>

$(function(){
  
  $("#id_subject,#id_message").addClass('form-control');
  $("#subbtn").click(function (event){
    
    let subValue=$("#id_subject").val().replace(/\s+/g,' ');
    let mesValue=$("#id_message").val().replace(/\s+/g,' ');

    if ((subValue==' ')  & (mesValue==' ')){
      
      console.log("Preventing Default");

      event.preventDefault();
    }

    if ((subValue=='') & (mesValue=='')){
      console.log("Preventing Default");
      event.preventDefault();
    }
  })
  
});
</script>
{%endblock%}
{%endblock%}

templates/password_change.html
{%extends 'base.html'%}

{%block breadcrumb%}
<li class="breadcrumb-item active">   <a href="/">Change Password</a></li>
    
{%endblock%}

{%block content%}

        <div class="row justify-content-center">
            <div class="container">
                <form action="" method="POST">
                    
                    {% csrf_token %}
                    {% include 'form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Change</button>
                </form>
            </div>
        </div>
{%endblock%}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post">
              {% csrf_token %}
              {% include 'form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
            <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/signup.html
{%extends 'base_accounts.html'%}

{%block content%}


        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                  <div class="card-body">
                    <h3 class="card-title">SignUp</h3>
                    <form method="post" novalidate>
                      {% csrf_token %}
                      {% include 'form.html' %}
                      <button type="submit" class="btn btn-primary btn-block">Create An Account</button>
                    </form>
                  </div>
                  <div class="card-footer text-muted text-center">
                   Already have an account? <a href="{% url 'login' %}">Login</a>
                  </div>
                </div>
              </div>
        </div>

{%endblock%}

templates/topics_post.html
{%extends 'base.html'%}


{%block breadcrumb%}
<li class="breadcrumb-item"href='/'>Boards</li>
<li class="breadcrumb-item" ><a href="{%url 'board_topics' topic.board.pk%}">{{ topic.board.name }}</a></li>
<li class="breadcrumb-item active">{{topic.subject}}</li>
{%endblock%}

{%block content%}
{%load static%}

<div class="mb-4">
  <a href="/board/{{topic.board.pk}}/topic/{{topic.pk}}/reply/" class="btn btn-primary" role="button">Reply</a>
</div>

{% for post in topic.posts.all %}
  <div class="card mb-2 {%if forloop.first%}border-dark{%endif%}">
    {% if forloop.first %}
    <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
  {% endif %}
    <div class="card-body p-3">
      <div class="row">
        
        <div class="col-2">
          <img src="{% static 'img/male_icon.png' %}" alt="{{ post.created_by.username }}" class="w-100">
          <small>Posts: {{ post.created_by.posts.count }}</small>
        </div>
        <div class="col-10">
          <div class="row mb-3">
            <div class="col-6">
              <strong class="text-muted">{{ post.created_by.username }}</strong>
            </div>
            <div class="col-6 text-right">
              <small class="text-muted">{{ post.created_at }}</small>
            </div>
          </div>
          {{ post.get_message_as_markdown }}
          {% if post.created_by == user %}
            <div class="mt-3">
              <a  class="btn btn-primary btn-sm" role="button" style="color:#fff;background-color: #646f7a;border-color: #030303;" href="/board/{{topic.board.pk}}/topic/{{topic.pk}}/post/{{post.pk}}/edit">Edit</a>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{%endfor%}
{%endblock%}